name: "TiddlyWiki Publish SPA"
description: "TiddlyWiki Publish SPA"

inputs:
  actions-folder:
    description: "Directory for published"
    required: false
    default: ".actions"
  tiddlywiki-lib-folder:
    description: "Directory for published"
    required: false
    default: "lib/tiddlywiki"
  tiddlers-directory:
    description: "Directory for published"
    required: true
    default: "."
  output-directory:
    description: "Directory for published"
    required: false
    default: '.tiddlywiki'
  version:
    description: "Frontend version of Logseq - git tag or SHA"
    required: false
    default: "5.3.6"

runs:
  using: "composite"
  steps:
    # - uses: actions/checkout@v4
    # - uses: oven-sh/setup-bun@v1
    #   with:
    #     bun-version: latest

    # - name: Install Dependency
    #   run: bun install # --production
    #   shell: bash

    - uses: actions/checkout@v4
      with:
        repository: oeyoews/tiddlywiki-publish
        path: ${{ inputs.actions-folder }}

    - uses: actions/checkout@v4
      with:
        repository: TiddlyWiki/TiddlyWiki5
        # @${{ inputs.version }}
        path: ${{ inputs.tiddlywiki-lib-folder }}

    - name: Build Page
      run: node ${{ inputs.actions-folder }}/publish.mjs --tiddlers-directory ${{ inputs.tiddlers-directory }} && ls -al
      shell: bash

    # - name: Upload artifact
    #   uses: actions/upload-pages-artifact@v3
    #   with:
    #     path: ${{ inputs.output-directory}}

    # - name: Deploy to GitHub Pages
    #   id: deployment
    #   uses: actions/deploy-pages@v4
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ${{ inputs.output-directory}}